### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by jnnks** [lox-space/lox#180]
Hi, I recently watched the RustConf 2024 video about Ephemerista and Lox and am looking for projects to contribute on a semi-regular basis. Since I have no astro* experience, I am mostly thinking about gruntwork, like this https://github.com/lox-space/lox/issues/125.

I have indirectly worked with Helge at Telespazio for a short while in case that has any weight :)

**Comment by helgee** [comment]
> I have indirectly worked with Helge at Telespazio for a short while in case that has any weight :)

Interesting 😉 

Contributions are very welcome although things are still very much in flux.
