### ISSUE TITLE
Implement an ephemeris file loader

### ISSUE THREAD

**Issue by matzipan** [lox-space/lox#2]
This task is to implement an ephemeris file loader similar to [the one in JuliaAstro](https://github.com/JuliaAstro/JPLEphemeris.jl). 

Ephemeris files can be found [here](https://naif.jpl.nasa.gov/pub/naif/generic_kernels/spk/planets/).

[Another implementation](https://www.imcce.fr/recherche/equipes/asd/calceph/) by CNRS. Or [this python one](https://github.com/brandon-rhodes/python-jplephem) here.

**Comment by helgee** [comment]
We will also want to be able to load several ephemeris files at once, e.g., planetary and satellites at the same time.

**Comment by matzipan** [comment]
Source material: https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/req/spk.html#SPK%20Required%20Reading
