### ISSUE TITLE
Proposal: Replace `continuous::Time` enum with trait

### ISSUE THREAD

**Issue by AngusGMorrison** [lox-space/lox#55]
# Summary

Replacing the `continuous::Time` enum with a `Time` trait will improve clarity for users, reduce boilerplate and enable stronger trait bounds on time-related functions.

# Problem

Currently, the `continuous::Time` enum serves one purpose: to associate a `TimeScale` with an instant.

```rust
/// `Time` represents a time in any of the supported continuous timescales.
#[derive(Debug, Copy, Clone, Eq, PartialEq)]
pub enum Time {
    TAI(TAI),
    TCB(TCB),
    TCG(TCG),
    TDB(TDB),
    TT(TT),
    UT1(UT1),
}
```

This has some disadvantages that point to a `Time` trait being more suitable.

1. Naming conventions are confusing: we have `TAI` the enum variant, `TAI` the timescale, `TAI` the instant struct, and `RawTime` the underlying instant struct.
```rust
    fn from_raw(scale: TimeScale, raw: RawTime) -> Self {
        match scale {
            TimeScale::TAI => Time::TAI(TAI(raw)),
            TimeScale::TCB => Time::TCB(TCB(raw)),
            TimeScale::TCG => Time::TCG(TCG(raw)),
            TimeScale::TDB => Time::TDB(TDB(raw)),
            TimeScale::TT => Time::TT(TT(raw)),
            TimeScale::UT1 => Time::UT1(UT1(raw)),
        }
    }
```
2. `Time` methods depend on boilerplate match statements to retrieve details about its variants' inner struct types. Even though these details are accessed in exactly the same way and the inner structs are exactly the same size, the compiler has no way of knowing.
```rust
    fn hour(&self) -> i64 {
        match self {
            Time::TAI(t) => t.hour(),
            Time::TCB(t) => t.hour(),
            Time::TCG(t) => t.hour(),
            Time::TDB(t) => t.hour(),
            Time::TT(t) => t.hour(),
            Time::UT1(t) => t.hour(),
        }
    }

    fn minute(&self) -> i64 {
        match self {
            Time::TAI(t) => t.minute(),
            Time::TCB(t) => t.minute(),
            Time::TCG(t) => t.minute(),
            Time::TDB(t) => t.minute(),
            Time::TT(t) => t.minute(),
            Time::UT1(t) => t.minute(),
        }
    }

    fn second(&self) -> i64 {
        match self {
            Time::TAI(t) => t.second(),
            Time::TCB(t) => t.second(),
            Time::TCG(t) => t.second(),
            Time::TDB(t) => t.second(),
            Time::TT(t) => t.second(),
            Time::UT1(t) => t.second(),
        }
    }
...
```
3. Method and trait implementations are repeated many times. For example, `WallClock` is implemented for `RawTime`, for each of the instant structs (which delegate to `RawTime`), and for `Time` (which uses match statements to delegate to each of the instant structs). This is simpler to represent generically.
4. Without a unifying trait for instant structs, the expressiveness of our trait bounds is limited. For example, we can't specify that the generic trait below must accept only time types:
```rust
pub trait TimeScaleTransformer<T, U> {
    fn transform(&self, time: T) -> U;
}
```

# Proposal

Replace the `Time` enum with a `Time` trait implemented by the instants of each scale:
```rust
pub trait Time {
    fn scale(&self) -> TimeScale;
    fn seconds(&self) -> i64;
    fn attoseconds(&self) -> u64;
    fn raw(&self) -> RawTime;
}

impl Time for TAI {
  fn scale(&self) -> TimeScale {
     TimeScale::TAI
  }
 
  ...
}
```

The association between scale and instant becomes inherent to the `Time`, and no longer requires another similarly named enum to represent. This means we can also delete the enum's boilerplate match statements and trait implementations.

Users can instantiate times in the correct scale with one fewer level of indirection:
**Current**
```rust
impl Time {
  pub fn from_utc_datetime(scale: TimeScale, dt: UTCDateTime) -> Time { ... }
}
```
**Proposed**
```rust
impl TAI {
  pub fn from_utc_datetime(dt: UTCDateTime) -> TAI { ... }
}
```

We retain the ability to refer to `Time`s in general using generics:
```rust
fn do_something_with_a_time(t: impl Time) { ... }
```

We gain stricter type bounds on time-related functions:
```rust
pub trait TimeScaleTransformer<T: Time, U: Time> { ... }
```

Using the trait, crate users may also implement their own times if they wanted to do something crazy like working in historical time scales. Unlikely, but a free positive to my mind.

# Concerns/unknowns

I recall that the Python interface struggles with generics, but not the specifics of the issue. How would these limitations affect the proposed design?

**Comment by helgee** [comment]
Yes, I see the problem, these `match` statements are cleary becoming a PITA. I would propose a slightly different new design which is aligned with the way that the `TwoBody` trait implementations work right now.

## Rename `RawTime` to `UnscaledTime`

Like in the `TwoBody` case we should have a concretely-typed core that can be reused in the Python wrapper, i.e. `UnscaledTime` née `RawTime` should implement most of the logic (parsing, construction from datetimes etc.).

```rust
struct UnscaledTime {
    seconds: i64,
    attoseconds: u64,
}
```

## Time scales become empty structs that implement a marker trait

Analogous to celestial bodies and referece frames in the `TwoBody` case.

```rust
pub trait TimeScale {
    fn name(&self) -> &str;
    fn long_name(&self) -> &str;
    ...
}

struct TAI;

impl TimeScale for TAI {
    fn name(&self) -> &str {
        "TAI"
    }
    fn long_name(&self) -> &str {
        "International Atomic Time"
    }
}
```

## `Time` structs become a thin generic wrapper around `UnscaledTime`

```rust
struct Time<T: TimeScale> {
    scale: T,
    timestamp: UnscaledTime,
}

impl Time<T: TimeScale> {
    fn scale(&self) -> T {
        self.scale
    }
    ...
}
```

In the Python wrapper on the other hand this can be concretely typed

```rust
enum PyTimeScale {
    ...
}

struct PyTime {
    scale: PyTimeScale
    timestamp: UnscaledTime
}
```

## Transformations

Transformations could be modelled after the `From` and `Into` traits from `std`.

```rust
pub trait TransformScale<T, S>
where
    T: TimeScale + Copy,
    S: TimeScale + Copy,
{
    fn output_scale(&self) -> S;
    fn offset(&self, time: Time<T>) -> TimeDelta;
}

#[derive(Debug, Copy, Clone, Eq, PartialEq)]
pub struct TaiToTt;

impl TransformScale<TAI, TT> for TaiToTt {
    fn output_scale(&self) -> TT {
        TT
    }

    fn offset(&self, _time: Time<TAI>) -> TimeDelta {
        TimeDelta {
            seconds: 32,
            attoseconds: 184 * 10u64.pow(15),
        }
    }
}

pub trait FromScale<T: TimeScale + Copy> {
    type Output: TimeScale + Copy;

    fn from_scale(
        time: Time<T>,
        transform: impl TransformScale<T, Self::Output>,
    ) -> Time<Self::Output>;
}

impl<S: TimeScale + Copy, T: TimeScale + Copy> FromScale<S> for Time<T> {
    type Output = T;

    fn from_scale(
        time: Time<S>,
        transform: impl TransformScale<S, Self::Output>,
    ) -> Time<Self::Output> {
        let timestamp = time.timestamp + transform.offset(time);
        Self {
            scale: transform.output_scale(),
            timestamp,
        }
    }
}

pub trait IntoScale<T: TimeScale + Copy> {
    type Input: TimeScale + Copy;

    fn into_scale(self, transform: impl TransformScale<Self::Input, T>) -> Time<T>;
}

impl<U: TimeScale + Copy, T: TimeScale + Copy> IntoScale<U> for Time<T> {
    type Input = T;

    fn into_scale(self, transform: impl TransformScale<Self::Input, U>) -> Time<U> {
        Time::from_scale(self, transform)
    }
}
```

The user-facing API would then work like this:

```rust
let tai = Time::new(TAI, ...);
let tt = tai.into_scale(TaiToTt);
let tt1 = Time::from_scale(tai, TaiToTt);
```

## Default Transformations

We could potentially provide default transformations like shown below:

```rust
impl Time<TT> {
    pub fn into_tt(self) -> Time<TT> {
        self
    }
}

impl Time<TAI> {
    pub fn into_tt(self) -> Time<TT> {
        Time::from_scale(self, TaiToTt)
    }
}

```

## Downstream changes

The `time` field will need to move out of the `*State` structs and into the generic `TwoBody` implementations. This is not a problem because the field was not used in the `impl`s of the low-level structs.

```rust
pub struct Cartesian<T, S, R>
where
    T: PointMass + Copy,
    S: ReferenceFrame + Copy,
    R: TimeScale + Copy,
{
    state: CartesianState,
    origin: T,
    frame: S,
    time: Time<R>,
}
```

**Comment by helgee** [comment]
A few simplifications...

## Time scales should derive `Default`

This saves a lot of headaches later on.

```rust
pub trait TimeScale: Default {
    fn new() -> Self {
        Self::default()
    }
    fn acronym(&self) -> &'static str;
    fn name(&self) -> &'static str;
}

#[derive(Debug, Copy, Clone, Eq, PartialEq, Default)]
pub struct TAI;
```

## `ScaleTransform` née `TransformScale` should transform instead of just returning an offset

They should also handle `UnscaledTime` to be easier to use on the Python side

```rust
pub trait ScaleTransform<T, S>
where
    T: TimeScale + Copy,
    S: TimeScale + Copy,
{
    fn transform_unscaled(&self, time: UnscaledTime) -> UnscaledTime;

    fn transform(&self, time: Time<T>) -> Time<S> {
        let timestamp = self.transform_unscaled(time.timestamp);
        Time::from_unscaled(S::new(), timestamp)
    }
}

#[derive(Debug, Copy, Clone, Eq, PartialEq)]
pub struct TaiToTt;

impl TaiToTt {
    const OFFSET: TimeDelta = TimeDelta {
        seconds: 32,
        attoseconds: 184 * 10u64.pow(15),
    };
}

impl ScaleTransform<TAI, TT> for TaiToTt {
    fn transform_unscaled(&self, time: UnscaledTime) -> UnscaledTime {
        time + Self::OFFSET
    }
}
```

## `FromScale` and `IntoScale` are not strictly necessary

I would still like to keep them because they will mirror other transformation methods in `coords`, e.g. `into_origin` (working title) will take an ephemeris as an argument. I will try to simplify them further.

## Default transformations should just implement `std::From`

```rust
impl From<Time<TAI>> for Time<TT> {
    fn from(tai: Time<TAI>) -> Self {
        TaiToTt.transform(tai)
    }
}
```

**Comment by helgee** [comment]
`FromScale` and `IntoScale` are in fact just an `impl`:

```rust
impl<T: TimeScale + Copy> Time<T> {
    pub fn from_scale<S: TimeScale + Copy>(
        time: Time<S>,
        transform: impl ScaleTransform<S, T>,
    ) -> Time<T> {
        transform.transform(time)
    }

    pub fn into_scale<S: TimeScale + Copy>(self, transform: impl ScaleTransform<T, S>) -> Time<S> {
        Time::from_scale(self, transform)
    }
}
```
