### ISSUE TITLE
RFC: Circular dependencies between lox-time and lox-eop

### ISSUE THREAD

**Issue by AngusGMorrison** [lox-space/lox#92]
I'm looking for opinions on how best to resolve circular dependencies between `lox-time` and `lox-eop`.

`lox-time` exposes fundamental types for working with time, such as `Time` and `TimeDelta`, and algorithms for transforming between timescales – including those for returning the delta between TAI and UTC (as a `TimeDelta`).

In order to provide a transformation for UT1 <-> TAI, `lox-time` requires access to `EarthOrientationParams`, exposed by `lox-eop`, which contains fields representing the delta between UT1 and UTC, and UT1 and TAI.

However, in order to calculate delta UT1-TAI, `lox-eop` needs access to functions and types from `lox-time`.

Further complicating things, unlike `AstroTime.jl`/`LeapSeconds.jl`, which implements the UTC/TAI algorithms such that they take MJDs as `f64` and return deltas as `f64` seconds, `lox-time` accepts and returns the `Time` and `TimeDelta` domain models. This is preferable for readability and consistency in the public interface, but means we have to give more thought to the crate structure.

## Proposed dependency graph

Time scale transformations -> EOP ->  Leap seconds -> Time primitives

### Time primitives crate

The base layer for all crates working with time. Includes `BaseTime`, `Time`, `TimeDelta` and `TimeScale`, along with the various `TimeScale` implementations.

### Leap seconds crate

Functions for calculating the `TimeDelta` between TAI and UTC.

### lox-eop

As is, with delta fields properly represented as `TimeDelta`s.

### Time scale transformations crate

Trait definitions and default implementations for all time scale transformations, operating on time primitives, leap second data, and observational data from the leap seconds crate.

Please let me know if I've overlooked anything that would cause this structure not to work, or if there's a better option I haven't considered.

**Comment by helgee** [comment]
That's too many crates, in my opinion.

I would suggest the following alternatives in descending order of preference:

- Keep the interface of `lox-eop` simple and low-level to enable other people to reuse it without subscribing to the whole lox-verse. Do the necessary augmentations within `lox-time`, e.g. building the UT1-TAI time series.
- Have the `lox-eop` crate downstream of `lox-time` and provide the `UT1` scale and the transformation provider from the former.

**Comment by helgee** [comment]
Yes, exactly.

**Comment by matzipan** [comment]
I concur with the fact that the initial proposal sounds too granular.
